# Generated by Django 5.2.6 on 2025-09-12 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='username',
            new_name='user',
        ),
    ]
